### ISSUE TITLE
Broken link

### ISSUE THREAD

**Issue by necantis** [lse-me314/assignment02#1]
The [rmd page of assignment 02](https://github.com/lse-me314/assignment02/blob/master/me314-assignment2-LASTNAME-FIRSTNAME.Rmd)  has a link to [assignment-2-complex-example-python.ipynb ](https://github.com/lse-me314/assignment02/blob/master/assignment-2-complex-example-python.ipynb) that doesn't work

**Comment by kbenoit** [comment]
Fixed in 7cf488d.
