### ISSUE TITLE
Missing code lines in the PDF to complete exercise 02 

### ISSUE THREAD

**Issue by necantis** [lse-me314/assignment02#2]
In the PDF version (slide 68) the code 

_library("reshape2", warn.conflicts = FALSE)
load("cmpdata.Rdata")
head(cmpdata)_
is not shown, whereas it is shown in the [github page ](https://github.com/lse-me314/lse-me314.github.io/blob/master/lecturenotes/ME314_day2.ipynb)

_In [37]:
library("reshape2", warn.conflicts = FALSE)
load("cmpdata.Rdata")
head(cmpdata)_

**Comment by kbenoit** [comment]
True - this is an issue with the pdf cutting some lines off. Sorry about that.
