### ISSUE TITLE
Wrong library to use for 

### ISSUE THREAD

**Issue by necantis** [lse-me314/assignment02#3]
In Slide 66 the library used is tidyverse and the code line is
spread(table2, key = type, value = count) %>% print()

Exercise b suggests using dplyr to perform a spread, but the suggested line does not work with this library, and there is not function that can easily perform that, according to the [documentation](https://cran.r-project.org/web/packages/dplyr/vignettes/dplyr.html)

**Comment by kbenoit** [comment]
True that **tidyverse** the package does not include `spread()`, but it loads the **tidyr** package, which does contain that function. See `?tidyr::spread`.
