### ISSUE TITLE
Idea: Using which() in exercise 6, as an alternative to subset()

### ISSUE THREAD

**Issue by necantis** [lse-me314/assignment02#4]
Source: Last example of https://github.com/lse-me314/assignment02/blob/master/how-to-manipulate-dataframe.ipynb

overall <- merge(rhpi_wideLong, rpdi_wideLong, by=c("country", "quarter"))
i = which(overall == "Australia")
head(overall[i,]) #filtered sample

**Comment by hugocruces** [comment]
Instead of previously define `overall`, one can simply write `merged[,1]`.
